### ISSUE TITLE
Crash with Gtk error when trying to open directory chooser

### ISSUE THREAD

**Issue by xylle** [BlobBackup/BlobBackup#44]
Hello,
when i launch app with normal user, the app crash with Gtk error when trying to open directory chooser.
```
Gtk-Message: 09:23:58.008: Failed to load module "canberra-gtk-module"
Gtk-Message: 09:23:58.008: Failed to load module "pk-gtk-module"
Gtk-Message: 09:23:58.008: Failed to load module "canberra-gtk-module"
Gtk-Message: 09:23:58.009: Failed to load module "pk-gtk-module"

(BlobBackup:1447794): Gtk-WARNING **: 09:24:01.692: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Paper/16x16/status/image-missing.png: Format d’image non reconnu (gdk-pixbuf-error-quark, 3)
Bail out! Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Paper/16x16/status/image-missing.png: Format d’image non reconnu (gdk-pixbuf-error-quark, 3)
Abandon (core dumped)

```
when i launch it at root, the app not crash, and app can load all module.

I use Fedora 33 (Workstation Edition), i download `https://github.com/BlobBackup/BlobBackup/releases/download/v1.0.0.beta2/BlobBackup_linux_amd64_v1.0.0.beta2.zip`, unzip and run BlobBackup

result of `rpm -qa | grep canberra`
```
libcanberra-0.30-23.fc33.x86_64
libcanberra-gtk2-0.30-23.fc33.x86_64
libcanberra-gtk3-0.30-23.fc33.x86_64
libcanberra-devel-0.30-23.fc33.x86_64
python3-canberra-0-0.25.git88c53cd.fc33.noarch
```
result of `rpm -qa | grep PackageKit`
```
PackageKit-glib-1.2.2-2.fc33.x86_64
PackageKit-1.2.2-2.fc33.x86_64
PackageKit-command-not-found-1.2.2-2.fc33.x86_64
PackageKit-gstreamer-plugin-1.2.2-2.fc33.x86_64
PackageKit-gtk3-module-1.2.2-2.fc33.x86_64

```

**Comment by bimbashrestha** [comment]
Hi can you try using the pip installer instead on linux. We've had issues in the past with the pre compiled binary not being compatible across multiple distros. The instructions should on the main README.

**Comment by xylle** [comment]
I have try the pip installer, but i dont find the main exec

**Comment by bimbashrestha** [comment]
Not quite sure what you mean. 

The executable after you install using pip should be in your PATH so you can just type 'blobbackup' and it should open up the gui. 

What python version are you using? I suspect there will be problems if you use a 2.x version. I've been using 3.7 so far.

**Comment by xylle** [comment]
I have python 3.9.2.

I try with 3.7.10 :
```
python3.7 -m venv venv3.7
source venv3.7/bin/activate
pip install --upgrade pip
pip install wheel
pip install .

blobbackup
Traceback (most recent call last):
  File "/srv/BlobBackup/venv3.7.10/bin/blobbackup", line 5, in <module>
    from blobbackup.application import main
  File "/srv/BlobBackup/venv3.7.10/lib64/python3.7/site-packages/blobbackup/application.py", line 10, in <module>
    from blobbackup.main_window import MainWindow
  File "/srv/BlobBackup/venv3.7.10/lib/python3.7/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/srv/BlobBackup/venv3.7.10/lib64/python3.7/site-packages/blobbackup/main_window.py", line 24, in <module>
    from blobbackup.backup_thread import BackupThread
  File "/srv/BlobBackup/venv3.7.10/lib/python3.7/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/srv/BlobBackup/venv3.7.10/lib64/python3.7/site-packages/blobbackup/backup_thread.py", line 3, in <module>
    from blobbackup.logger_wrapper import LoggerWrapper
  File "/srv/BlobBackup/venv3.7.10/lib/python3.7/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'blobbackup.logger_wrapper'
```

**Comment by bimbashrestha** [comment]
@xylle Ahh this is definitely a bug. I know what the issue is. I'll put up a fix later today, Thanks for testing it

**Comment by bimbashrestha** [comment]
@xylle Just fixed it in the main branch with https://github.com/BlobBackup/BlobBackup/commit/6f3429a4c6ae457249a67b3218a6a0254de498e0. Give it a try again. I believe it should work.

**Comment by xylle** [comment]
Thanks, work fine with python 3.7.10 and 3.9.2
Nice project,
